config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :tab_resource_types, only: [:index, :update] do
        delete 'form_value/:form_value_id', to: 'tab_resource_types#delete_value', on: :collection, as: :form_value
      end
    end
    resources :resource_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
      resources :custom_fields, controller: 'resource_types/custom_fields' do
        collection do
          post :update_positions
          post :update_values_positions
        end
      end
    end
  end
end

app/models/spree/custom_field.rb
module Spree
  class CustomField < Spree::Base
    acts_as_list
    before_save :fulfill_placeholder, if: lambda { |c| c.placeholder.empty? }
    after_save :destroy_options, if: lambda { |c| c.type != "Spree::DropdownField" && c.options.any? }
    after_save :touch_owner
    after_destroy :adjust_form_value
    belongs_to :owner, polymorphic: true
    has_one :form_value,                  class_name: Spree::FormValue,
                                          inverse_of: :custom_field,
                                          foreign_key: 'custom_field_id',
                                          dependent: :nullify

    has_one :taxon_filter,                class_name: Spree::Filter,
                                          inverse_of: :custom_field,
                                          foreign_key: 'custom_field_id',
                                          dependent: :nullify
    delegate :value, to: :form_value

    validates :label, :type, presence: true

    has_many :options,        class_name: Spree::DropdownOption,
                              foreign_key: 'dropdown_field_id',
                              inverse_of: :dropdown_field,
                              dependent: :destroy

    accepts_nested_attributes_for :options, allow_destroy: true

    default_scope { order(position: :asc) }

    def validate_value(form_value)
      value = form_value.value
      value = value.delete_if(&:blank?) if value.is_a?(Array)
      if required? && value.blank?
        form_value.errors.add :value, "#{label} can't be blank"
        add_validation_errors(form_value)
      end

      form_value
    end

    def add_validation_errors(form_value)
      fail NotImplementedError
    end

    private
    def destroy_options
      self.options.destroy_all
    end

    def fulfill_placeholder
      placeholder = label
    end

    def adjust_form_value
      if form_value
        form_value.update_columns({field_label: label, frontend_visible: frontend_visible})
      end
    end

    def touch_owner
      owner.update_attribute(:updated_at, Time.current)
    end
  end
end

app/controllers/spree/admin/resource_types/custom_fields_controller.rb
module Spree
  module Admin
    module ResourceTypes
      class CustomFieldsController < ResourceController
        append_before_action :load_resource, :filter_by_resource_type, except: :update_positions

        def update_values_positions
          params[:positions].each do |id, index|
            @custom_fields.find(id).update_column(:position, index)
          end

          respond_to do |format|
            format.js { render plain: 'Ok' }
          end
        end

        private
        def filter_by_resource_type
          @custom_fields = collection.where(
            owner_id: params[:resource_type_id],
            owner_type: 'Spree::ResourceType')
        end
      end
    end
  end
end

app/controllers/spree/admin/resource_types_controller.rb
module Spree
  module Admin
    class ResourceTypesController < ResourceController
      include FormBehaviors

      def update_values_positions
        params[:positions].each do |id, index|
          Spree::ResourceType.where(id: id).update_all(position: index)
        end

        respond_to do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js { render plain: 'Ok' }
        end
      end

      private

      def location_after_save
        edit_admin_resource_type_url(@resource_type)
      end

      def load_product
        @product = Spree::Product.find_by_param!(params[:product_id])
      end

      def permitted_resource_params
        params.require(:resource_type).permit(:name, custom_fields_attributes)
      end
    end
  end
end

app/views/spree/admin/resource_types/custom_fields/index.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(plural_resource_name(Spree::ResourceType)) %>
<% admin_breadcrumb(plural_resource_name(Spree::CustomField)) %>

<% if @custom_fields.any? %>
<table class="index sortable" id="listing_custom_fields" data-hook="listing-custom-fields" data-sortable-link="<%= update_values_positions_admin_resource_type_custom_fields_url(resource_type_id: params[:resource_type_id]) %>">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 35%">
    <col style="width: 40%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="option_header">
      <th class="no-border"></th>
      <th><%= Spree::CustomField.human_attribute_name(:label) %></th>
      <th><%= Spree::CustomField.human_attribute_name(:type) %></th>
      <th><%= Spree::CustomField.human_attribute_name(:required) %></th>
    </tr>
  </thead>
  <tbody>
    <% @custom_fields.each do |custom_field| %>
      <tr class="spree_custom_field <%= cycle('odd', 'even')%>" id="<%= spree_dom_id custom_field %>" data-hook="option_row">
        <td class="no-border"><span class="handle"></span></td>
        <td class="align-center"><%= custom_field.label %></td>
        <td class="align-center"><%= custom_field.type.split("::").last %></td>
        <td class="align-center"><%= custom_field.required %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="col-md-9 no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::CustomField,
                 new_resource_url: new_object_url %>
  </div>
<% end %>