config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :tab_resource_types, only: [:index, :update] do
        delete 'form_value/:form_value_id', to: 'tab_resource_types#delete_value', on: :collection, as: :form_value
      end
    end
    resources :resource_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
      resources :custom_fields, controller: 'resource_types/custom_fields' do
        collection do
          post :update_positions
          post :update_values_positions
        end
      end
    end
  end
end

app/controllers/spree/admin/resource_types/custom_fields_controller.rb
module Spree
  module Admin
    module ResourceTypes
      class CustomFieldsController < ResourceController
        append_before_action :load_resource, :filter_by_resource_type, except: :update_positions

        def update_values_positions
          params[:positions].each do |id, index|
            @custom_fields.find(id).update_column(:position, index)
          end

          respond_to do |format|
            format.js { render plain: 'Ok' }
          end
        end

        private
        def filter_by_resource_type
          @custom_fields = collection.where(
            owner_id: params[:resource_type_id],
            owner_type: 'Spree::ResourceType')
        end
      end
    end
  end
end

app/controllers/spree/admin/resource_types_controller.rb
module Spree
  module Admin
    class ResourceTypesController < ResourceController
      include FormBehaviors

      def update_values_positions
        params[:positions].each do |id, index|
          Spree::ResourceType.where(id: id).update_all(position: index)
        end

        respond_to do |format|
          format.html { redirect_to admin_product_variants_url(params[:product_id]) }
          format.js { render plain: 'Ok' }
        end
      end

      private

      def location_after_save
        edit_admin_resource_type_url(@resource_type)
      end

      def load_product
        @product = Spree::Product.find_by_param!(params[:product_id])
      end

      def permitted_resource_params
        params.require(:resource_type).permit(:name, custom_fields_attributes)
      end
    end
  end
end

app/views/spree/admin/resource_types/_cocoon_setup.js.erb
bind_input_text = function(first_elem, second_elem){
  first_elem.keyup(function(e){
    if(second_elem.data('fieldChanged') == undefined){
      second_elem.val(first_elem.val());
    }
  });
}

trigger_field_changed = function(elem){
  if(elem.val().length != 0){
    elem.data('fieldChanged', true);
  }
  elem.one('focus', function(e1){
    elem.one('keypress', function(e2){
      elem.data('fieldChanged', true);
    });
  });
}

adjust_placeholder = function(limits_elem, limits_obj, clear){
  min_limit = limits_elem.find("input[id*=min]");
  min_limit.attr("placeholder", limits_obj.min);
  max_limit = limits_elem.find("input[id*=max]");
  max_limit.attr("placeholder", limits_obj.max);
  if(clear == true){
    min_limit.val('');
    max_limit.val('');
  }
}

select_change_func = function(insertedItem, js_select_elem){
  instance_label_input = insertedItem.find('.field-label');
  instance_placeholder_input = insertedItem.find('.field-placeholder');
  trigger_field_changed(instance_placeholder_input);
  bind_input_text(instance_label_input, instance_placeholder_input);

  select_elem = $(js_select_elem);
  selected_option = select_elem.val();
  nested_field_elem = $(insertedItem);
  instance_options_form = nested_field_elem.find(".options-holder");
  instance_limit_fields_elem = nested_field_elem.find(".limit-fields");
  check_boxes_def_elem = nested_field_elem.find(".check-box-def");
  instance_limit_fields_elem.hide();
  if(selected_option == "Spree::DropdownField"){
    instance_options_form.show();
    check_boxes_def_elem.show();
  }else{
    instance_options_form.find(".items").empty();
    instance_options_form.hide();
    check_boxes_def_elem.hide();
    if(selected_option == "Spree::IntegerField"){
      instance_limit_fields_elem.show();
      adjust_placeholder(instance_limit_fields_elem, {min:"Min number", max:"Max number"}, true);
    }
    if(selected_option == "Spree::DateField"){
      instance_limit_fields_elem.show();
      adjust_placeholder(instance_limit_fields_elem, {min:"Min date of format yyyy/mm/dd", max: "Min date of format yyyy/mm/dd"}, true)
    }
  }
};

dropdown_field_disabling = function(){
  g_select_elem = $(this);
  g_select_elem.change(select_change_func);
  field_elem = g_select_elem.closest(".custom-field-item");

  label_input = field_elem.find('.field-label');
  placeholder_input = field_elem.find('.field-placeholder');
  trigger_field_changed(placeholder_input);
  bind_input_text(label_input, placeholder_input);

  options_form = field_elem.find(".options-holder");
  selected_option = g_select_elem.val();
  options_items = options_form.find(".items");
  limit_fields_elem = field_elem.find(".limit-fields");
  check_boxes_def_elem = field_elem.find(".check-box-def");
  limit_fields_elem.hide();
  if(selected_option == "Spree::DropdownField"){
    options_form.show();
    check_boxes_def_elem.show();
  }else{
    options_items.empty();
    options_form.hide();
    check_boxes_def_elem.hide();
    if(selected_option == "Spree::IntegerField"){
      limit_fields_elem.show();
      adjust_placeholder(limit_fields_elem, {min:"Min number", max:"Max number"}, false);
    }
    if(selected_option == "Spree::DateField"){
      limit_fields_elem.show();
      adjust_placeholder(limit_fields_elem, {min:"Min date of format yyyy/mm/dd", max: "Min date of format yyyy/mm/dd"}, false);
    }
  }
}

split_pathname = location.pathname.split('/');
if(split_pathname[split_pathname.length-1] == 'edit' || $("form input[type='hidden'][name='_method']").val() == 'patch'){
  $(".type_select select").each(dropdown_field_disabling);
}

$("div#resource-fields-container").on('cocoon:after-insert', function(e, insertedItem) {
  if(insertedItem.hasClass("custom-field-item")){
    insertedItem.find(".type_select select").change(function(event){
      select_change_func(insertedItem, this);
    }).change();
    insertedItem.find('.option-links a')
      .data("association-insertion-method", 'append')
      .data('data-association-insertion-node', function(link){
      return link.parents('.options-holder').find('items');
    });
  }
});

app/views/spree/admin/resource_types/_form.html.erb
<div data-hook="admin_resource_type_form_fields" class="align-center row">
  <div class="col-md-12">
    <%= f.field_container :name do %>
      <%= f.label :name, class: 'required text-left' %>
      <%= f.text_field :name, :class => "fullwidth" %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
</div>

<div data-hook="admin_resource_type_custom_fields_form" class="align-center" id="resource-fields-container">
  <fieldset class="no-border-bottom">
    <legend align="center">Resource Fields</legend>
    <div id="custom_fields">
      <%= f.fields_for :custom_fields do |field_form| %>
        <%= render :partial => 'spree/admin/shared/custom_fields', :locals => { :f => field_form } %>
      <% end %>
      <div class="links field-links">
        <%= link_to_add_association 'Add Field', f, :custom_fields,
          partial: 'spree/admin/shared/custom_fields', class: 'button' %>
      </div>
    </div>
  </fieldset>
</div>

<%= javascript_tag do %>
  <%= render(partial: 'cocoon_setup', handlers: [:erb], formats: [:js]) %>
<% end %>

app/views/spree/admin/resource_types/edit.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(link_to plural_resource_name(Spree::ResourceType), spree.admin_resource_types_path) %>
<% admin_breadcrumb(@resource_type.name) %>


<% content_for :page_actions do %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @resource_type } %>

<%= form_for [:admin, @resource_type] do |f| %>

  <fieldset class="no-border-bottom">
    <legend><%= Spree::ResourceType.model_name.human %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/resource_types/index.html.erb
<% admin_breadcrumb(link_to plural_resource_name(Spree::Product), spree.admin_products_path) %>
<% admin_breadcrumb(plural_resource_name(Spree::ResourceType)) %>


<% content_for :page_actions do %>
  <% if can?(:create, Spree::ResourceType) %>
    <li id="new_ot_link">
      <%= button_link_to Spree.t(:new_resource_type), new_admin_resource_type_url, { :remote => true, :id => 'new_resource_type_link' } %>
    </li>
  <% end %>
<% end %>

<div id="new_resource_type"></div>

<% if @resource_types.any? %>
<table class="index sortable" id="listing_resource_types" data-hook="listing-resource-types" data-sortable-link="<%= update_values_positions_admin_resource_types_url %>">
  <colgroup>
    <col style="width: 10%">
    <col style="width: 35%">
    <col style="width: 40%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="option_header">
      <th class="no-border"></th>
      <th><%= Spree::ResourceType.human_attribute_name(:name) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @resource_types.each do |resource_type| %>
      <tr class="spree_resource_type <%= cycle('odd', 'even')%>" id="<%= spree_dom_id resource_type %>" data-hook="option_row">
        <td class="no-border"><span class="handle"></span></td>
        <td class="align-center"><%= resource_type.name %></td>
        <td class="actions">
          <%= link_to_with_icon('list', '',
            admin_resource_type_custom_fields_path(resource_type_id: resource_type.id)) %>
          <% if can?(:update, resource_type) %>
            <%= link_to_edit(resource_type, :class => 'admin_edit_resource_type', :no_text => true) %>
          <% end %>
          <% if can?(:destroy, resource_type) %>
            <%= link_to_delete(resource_type, :no_text => true) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="col-md-9 no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                 resource: Spree::ResourceType,
                 new_resource_url: new_object_url %>
  </div>
<% end %>

app/views/spree/admin/resource_types/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @resource_type } %>

<%= form_for [:admin, @resource_type] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:new_resource_type) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/resource_types/new.js.erb
$("#new_resource_type").html('<%= escape_javascript(render :template => "spree/admin/resource_types/new", :formats => [:html], :handlers => [:erb]) %>');
$("#new_resource_type_link").parent().hide();