config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :tab_resource_types, only: [:index, :update] do
        delete 'form_value/:form_value_id', to: 'tab_resource_types#delete_value', on: :collection, as: :form_value
      end
    end
    resources :resource_types do
      collection do
        post :update_positions
        post :update_values_positions
      end
      resources :custom_fields, controller: 'resource_types/custom_fields' do
        collection do
          post :update_positions
          post :update_values_positions
        end
      end
    end
  end
end

app/controllers/spree/admin/tab_resource_types_controller.rb
module Spree
  module Admin
    class TabResourceTypesController < Spree::Admin::BaseController
      include SubmittableBehaviors
      before_action :find_product
      helper_method :formatted_value

      def index
        @resource_type = @product.resource_type
      end

      # It actually updates
      def update
        @variant = Spree::Variant.find(params[:id])
        @resource_type = @product.resource_type

        @variant.assign_attributes(variant_submittable_params)
        @variant.form_values.map(&:save) # It tries to save each one on itself.
        if @variant.save
          respond_with(@product) do |format|
            format.html { redirect_to(
              spree.admin_product_tab_resource_types_path(product_id: @product.id),
              flash: { notice: Spree.t(:values_updated, scope: [:admin, :resource_types]) })
            }
          end
        else
          render :index
        end
      end

      def delete_value
        form_value = Spree::FormValue.find(params[:form_value_id])
        if form_value.destroy
          respond_with(@product) do |format|
            format.html { redirect_to(
              spree.admin_product_tab_resource_types_path(product_id: @product.id),
              flash: { notice: Spree.t(:value_deleted, scope: [:admin, :resource_types]) })
            }
          end
        else
          render :index
        end
      end

      def formatted_value(value)
        if value.is_a?(Array)
          value.reject(&:blank?).join(',')
        else
          value
        end
      end

      private
      def find_product
        @product = Spree::Product.friendly.find(params[:product_id])
      end

      def variant_submittable_params
        params.require(:variant).permit(form_values_attributes)
      end
    end
  end
end

app/views/spree/admin/tab_resource_types/_form_values.html.erb
<div class="nested-fields custom-form-field col-md-3">
  <div class="field">
    <% if f.object.custom_field.present? %>
      <% field = "#{f.object.custom_field.type}Presenter".constantize.new(f.object.custom_field) %>
      <%= f.input :custom_field_id, as: :hidden, value: field.id %>
      <%= f.input :value, {
        label: field.display_label,
        input_html: field.input_html,
        required: field.required_html,
        value: field.value,
        wrapper_html: field.wrapper_html,
      }.merge(field.options) %>
    <% else %>
      <%= f.label f.object.field_label %>
      <%= link_to form_value_admin_product_tab_resource_types_path(product_id: @product.id, form_value_id: f.object.id),
        id: 'delete-value', class: 'showhim', method: :delete,
        data: { method: :delete, confirm: 'Are you sure?' } do %>
        X
      <% end %>
      <div class="showme-left">
        This field is blocked because it was deleted at the source.
        Click at this button to delete it from here as well.
      </div>
      <%= f.text_field :value, value: formatted_value(f.object.value), disabled: true %>
    <% end %>
  </div>
</div>

app/views/spree/admin/tab_resource_types/index.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Extra Fields"} %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @variant } %>

<% admin_breadcrumb(Spree.t(:resource_fields, scope: [:admin, :tab])) %>

<%= simple_form_for Spree::VariantPresenter.new(@product.master), url: spree.admin_product_tab_resource_type_path(@product.master, product_id: @product.id) do |f| %>

  <fieldset class="no-border-bottom">
    <legend><%= @resource_type.name.singularize.titleize + " Fields"%></legend>

    <div class="row">
      <%= f.fields_for :form_values do |value_form| %>
        <%= render :partial => 'spree/admin/tab_resource_types/form_values', :locals => { :f => value_form } %>
      <% end %>
    </div>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update') %>
    </div>
  </fieldset>
<% end %>